### ISSUE TITLE
App.js

### ISSUE THREAD

**Issue by jlag34** [Teched25/Jammming-Codecademy#2]
Your App.js file has a few good things and a few things that need improvement. First, good job adding all of the necessary methods. Also, most of the methods do just what they are suppose to. The one that needs a second look is `addTrack`. First issue with it is that you add all tracks. You are suppose to first check if the track exists in the playlist already and if it does, don't add it. Second, you mutate state when you do `push` on line 29. Try something like this:

```
addTrack(track) {
    const tracks = this.state.playlistTracks.concat(track);
    this.setState({ playlistTracks: tracks });
```

`concat` returns a new array. You didn't mutate state in `removeTrack` because you used the `filter` method which also returns a new array.

**Comment by Teched25** [comment]
Thank for the recommendation I will work on it.
